### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by aytekinar**
Fixed typo in demanding `super user` powers

### CODE REVIEW

**Comment by mfalt** [comment]
Thanks! May I ask how you you stumbled upon this?

**Comment by aytekinar** [comment]
Hey! I am a PhD student at KTH. Yesterday we were searching for `Control`-related packages in `Julia` with my colleague, and we came across your repository. We had also started a project involving system identification and control analysis/synthesis tools, and we were checking what is available currently in the official repos at JuliaLang.

This merge request was just some fun/luck :) I wanted to check the configs hoping to find some useful dotFiles, and I just noticed the typo, that's it :)

**Comment by mfalt** [comment]
Ah, yeah I just started the configs repo, and never intended on anyone else to use it so probably nothing useful. I'm glad that you are interested in Control packages in Julia. We are currently two PhD students at LTH working on the ControlSystems package, you are more than welcome to contribute. Any feedback on the usability and lacks of features/bugs would also be welcome.

**Comment by aytekinar** [comment]
Actually, we are also two PhD students right now who have recently made the switch from MATLAB to Julia for our research. We had a summer project last year, which involved interested (BSc-level) students getting their hands dirty on programming and trying to make a course material consisting of control and identification toolboxes in Julia.

We would like to contribute to your repository, definitely, and for this purpose, we have contacted our professors responsible for the above mentioned Julia project. Most likely we would be merging the system identification part with yours and maybe suggesting some changes/additions to the control part to start with.

How about making a message group among each other to talk at some point on what to include and which way to proceed?

My friend is Niklas Everitt (@neveritt) and I am Arda Aytekin, both of us at KTH, by the way.

**Comment by mfalt** [comment]
Sounds like a great idea, I've created this room
https://gitter.im/JuliaControl/public
where we can talk. Not sure if this is the best platform, but it seems to work fine.

**Pull request merged**
